packages:
  - lib/*
  - app
  - workers/*

catalog:
  '@cloudflare/vitest-pool-workers': ^0.10.10
  '@cloudflare/workers-types': ^4.20251118.0
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.4
  '@tailwindcss/vite': ^4.1.17
  '@types/luxon': ^3.7.1
  '@types/node': ^24.10.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  compromise: ^14.14.4
  compromise-speech: ^0.1.1
  compromise-syllables: ^0.0.6
  hono: ^4.10.6
  lucide-react: ^0.553.0
  luxon: 3.7.2
  msgpackr: ^1.11.5
  prettier: ^3.6.2
  quick-lru: 7.3.0
  react-router-dom: ^7.9.6
  simple-statistics: ^7.8.8
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite: ^7.2.2
  vitest: ^4
  wrangler: 4.47.0
  zod: 4.1.12

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp
  - workerd
